### ISSUE TITLE
Error PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backdropcmsorg.menu_custom' doesn't exist:

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/menu_admin_per_menu#1]
Thanx @jenlampton for adding the user guide menu and the docs content type for those of us that want to contribute to the user guide (https://github.com/backdrop-ops/backdropcms.org/issues/55).

When visiting Structure > Menus > List menus (`https://backdropcms.org/admin/structure/menu/list`) from the newly added admin menu per user, I get the following error:

```
PDOException: SQLSTATE[42S02]: Base table or view not
found: 1146 Table 'backdropcmsorg.menu_custom' doesn't
exist: SELECT * FROM {menu_custom} ORDER BY title; Array ( )
in _menu_admin_per_menu_menu_overview_page() (line 50 of
/home/backdrop/repo/www/modules/contrib
/menu_admin_per_menu/menu_admin_per_menu.module).
```

**Comment by jenlampton** [comment]
Welp, not sure how I missed that one!

**Comment by jenlampton** [comment]
Fix included in latest release: https://github.com/backdrop-contrib/menu_admin_per_menu/releases/tag/1.x-1.1.1

**Comment by klonos** [comment]
Thanx!
